name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
              echo "Hello World"
              echo "Hellow World from Git Action with multiline shell commands"
      - name: print good bye
        run: echo "Done - bye!"
